version: '3.8'

services:
  api:
    container_name: todo-api
    image: node:14.17-alpine3.14
    command: [sh, -c, "npm run start:dev"]
    env_file:
      - .env
      - .env.development
    environment:
      - NODE_ENV=development
    ports:
      - 3010:3000
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    depends_on:
      - database

  database:
    container_name: todo-db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123456

  adminer:
    image: adminer
    ports:
      - 8070:8080
